version: "3"
services:
  wordpress:
    depends_on:
      - "mysql"
    image: wordpress:5.2.2
    volumes:
      - ./wordpress/themes/takakisan:/var/www/html/wp-content/themes/takakisan
    ports:
      - "5000:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  mysql:
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: "local"
  wordpress:
    driver: "local"
